### ISSUE TITLE
Determine BIDS-friendly naming scheme for Webknossos datasets with multiple imaging layers

### ISSUE THREAD

**Issue by kabilar** [lincbrain/webknossos#19]
## Description

We are working towards naming all assets on the [LINC Data Platform](https://lincbrain.org) according to the [BIDS specification](https://bids-specification.readthedocs.io/en/stable/).  Webknossos datasets will consist of several assets from the LINC Data Platform as imaging/color layers.  Let's aim to name these Webknossos datasets according to the BIDS specification (or as close as possible).

## Goals

1. Determine a standard way to name these Webknossos datasets with multiple imaging layers.
2. Document this naming scheme on the [LINC docs](https://docs.lincbrain.org/).

Thank you.

**Comment by kabilar** [comment]
Thanks @jingjingwu1225.  Sounds great.  Will we be creating Webknossos datasets that are comprised of a histology image plus the previous generated annotations from Vaanathi's work that are now in the Zarr format?

**Comment by jingjingwu1225** [comment]
Hi @kabilar, thanks for the reminder. Yes, after we got the updated groundtruth annotations from Vaanathi's work I'll upload them to lincbrain and add both datasets itself and masks to webknossos in one dataset, and delete the current one. The annotations will be saved separately with the dataset but added as layers in webknossos.

**Comment by kabilar** [comment]
Thanks @jingjingwu1225.  How would you name these Webknossos datasets with multiple layers?  I presume that this would be a case where this is not a 1-1 mapping between the naming on lincbrain.org and on Webknossos.

**Comment by kabilar** [comment]
@jingjingwu1225 @jssyq @elissabell Thanks for the discussion last week.  We decided that Webknossos datasets with multiple layers are currently needed in order to visualize the previously generated annotations.  So these Webknossos datasets will be named as described in #20 with Vaanathi Sundaresan's initials.

**Comment by kabilar** [comment]
Fixed in https://github.com/lincbrain/linc-docs/pull/27
