### ISSUE TITLE
Determine BIDS-friendly naming scheme for Webknossos annotations

### ISSUE THREAD

**Issue by kabilar** [lincbrain/webknossos#20]
## Description

We are working towards naming all assets on the [LINC Data Platform](https://lincbrain.org) according to the [BIDS specification](https://bids-specification.readthedocs.io/en/stable/).  As Webknossos annotations will be uploaded to the LINC Data Platform, let's aim to name these annotation files according to the BIDS specification (or as close as possible).  We can reference the BIDS specification for [discrete segmentations](https://bids-specification.readthedocs.io/en/stable/derivatives/imaging.html#discrete-segmentations).  ~This task is a bit complicated as Webknossos datasets will consist of several assets from the LINC Data Platform as imaging/color layers, so this issue depends on #19.~

## Goals

1. Determine a standard way to name these Webknossos annotations ~that are based on Webknossos datasets with multiple imaging layers~.
2. Document this naming scheme on the [LINC docs](https://docs.lincbrain.org/).

Thank you.

**Comment by jssyq** [comment]
Hi Kabi, the LINC documentation site can't be opened @kabilar

**Comment by jssyq** [comment]
Nevermind, it works on the laptop

**Comment by jingjingwu1225** [comment]
Hi @kabilar, after discussion, we agreed on adding initials of annotator after label desc and a suffix of _dseg to represent it's discrete segmentations. For a dataset with name of sub-MR243_sample-slice0000slice0004_stain-LY_DF on webknossos, its corresponding annotations will have name of sub-MR243_sample-slice0000slice0004_stain-LY_DF_desc-JW_dseg. We're working on adding the naming scheme on LINC docs. Thanks!

**Comment by kabilar** [comment]
Thank you, @jingjingwu1225 @jssyq.  I have left some suggestions in https://github.com/lincbrain/linc-docs/pull/21.

**Comment by kabilar** [comment]
cc @ayendiki

**Comment by kabilar** [comment]
Crossposting the discussion with the BIDS team on using the `desc` entity: https://github.com/bids-standard/bids-specification/issues/1959

**Comment by kabilar** [comment]
After discussion with the team, we decided that these annotations will be performed on a single layer, so I updated the initial comment.

**Comment by kabilar** [comment]
Fixed in https://github.com/lincbrain/linc-docs/pull/21.  Thank you, @jssyq @jingjingwu1225 @elissabell.
